In [1]:
def fun(x):
    if x>2:
        return True

In [4]:
list1=[1,2,4,5,6,7,8,9,10]
tuple1=(1,2,3,4,5)

In [7]:
a=tuple(filter(fun,tuple1))

In [8]:
a

(3, 4, 5)

In [21]:
func= lambda x:x**2

In [22]:
func(2)

4

In [23]:
list1

[1, 2, 4, 5, 6, 7, 8, 9, 10]

In [26]:
list(map(lambda x:x**2,list1))

[1, 4, 16, 25, 36, 49, 64, 81, 100]

In [28]:
def add(x):
    return x+2

In [29]:
list(map(add,list1))

[3, 4, 6, 7, 8, 9, 10, 11, 12]

In [30]:
def mult(x,y):
    return x*y

In [31]:
list1

[1, 2, 4, 5, 6, 7, 8, 9, 10]

In [32]:
list2

[10, 20, 30, 0, 11, 22]

In [34]:
print(list(map(mult,list1,list2)))

[10, 40, 120, 0, 66, 154]


## Exceptional Handling

In [12]:
a= input('Enter the number')
b= input('Enter the number')
try:
    div= a/b 
except TypeError:
    print('string cannot divisible')

Enter the number2
Enter the number2
string cannot divisible


In [15]:
a= int(input('Enter the number'))
b= int(input('Enter the number'))
try:
    div= a/b 
    print(div)
except ZeroDivisionError:
    print('Number cannot be divisible by zero')
    

Enter the number2
Enter the number0
Number cannot be divisible by zero


In [16]:
list1=[1,2,3,4]
list2=[10,20,30,40]

In [19]:
list1/list2

TypeError: unsupported operand type(s) for /: 'list' and 'list'

## NUMPY

In [20]:
import numpy as np

In [37]:
one_dim= np.array([1,2,3,4,5])

In [38]:
one_dim

array([1, 2, 3, 4, 5])

In [39]:
type(one_dim)

numpy.ndarray

In [40]:
one_dim.ndim

1

In [41]:
one_dim.shape

(5,)

In [42]:
one_dim.size

5

In [52]:
one_dim= np.array([2,4,6,8,10])
one_dim

array([ 2,  4,  6,  8, 10])

In [51]:
one_dim1

array([ 2,  4,  6,  8, 10])

In [34]:
one_dim

array([ 2,  4,  6,  8, 10])

In [35]:
one_dim

array([ 2,  4,  6,  8, 10])

In [49]:
one_dim/one_dim1

array([1., 1., 1., 1., 1.])

In [45]:
one_dim1.max()

10

In [46]:
one_dim1

array([ 2,  4,  6,  8, 10])

In [47]:
one_dim1.min()

2

In [48]:
one_dim1.mean()

6.0

In [53]:
np.max(one_dim)

10

In [54]:
np.min(one_dim)

2

In [55]:
np.mean(one_dim)

6.0

In [56]:
np.median(one_dim)

6.0

In [57]:
np.sum(one_dim)

30

In [58]:
one_dim

array([ 2,  4,  6,  8, 10])

In [59]:
np.insert(one_dim,2,100)

array([  2,   4, 100,   6,   8,  10])

In [60]:
one_dim

array([ 2,  4,  6,  8, 10])

In [62]:
one_dim[2:5]

array([ 6,  8, 10])

In [63]:
list=[1,2,3,4]

In [64]:
np.array(list)

array([1, 2, 3, 4])

In [66]:
one_dim=np.array([1,3,3,4,5,6,7,7,8])

In [67]:
np.unique(one_dim)

array([1, 3, 4, 5, 6, 7, 8])

In [68]:
one_dim

array([1, 3, 3, 4, 5, 6, 7, 7, 8])

In [69]:
np.delete(one_dim,1)

array([1, 3, 4, 5, 6, 7, 7, 8])

In [87]:
list1=[]
n= int(input('Enter the count'))
for i in range(0,n):
    var= int(input('Enter the data'))
    list1.append(var)
    one_dim2=np.array(list1)
    two_dim=one_dim2.reshape()
    

Enter the count2
Enter the data1
Enter the data2


In [88]:
one_dim2

array([1, 2])

## Two_dimensional_array

In [89]:
two_dim= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [90]:
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
type(two_dim)

numpy.ndarray

In [92]:
two_dim.ndim

2

In [93]:
two_dim.shape

(3, 3)

In [94]:
two_dim.size

9

In [96]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [105]:
two_dim= np.arange(0,24,2).reshape(3,4)

In [106]:
two_dim

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])