In [1]:
import numpy as np

In [12]:
two_dim= np.random.randint(0,20,16).reshape(4,4)

In [13]:
two_dim

array([[10, 18, 11, 17],
       [ 3, 13, 14,  4],
       [ 5, 13, 10,  7],
       [17,  3,  6,  9]])

In [14]:
a,b=np.hsplit(two_dim,2)

In [15]:
a

array([[10, 18],
       [ 3, 13],
       [ 5, 13],
       [17,  3]])

In [16]:
b

array([[11, 17],
       [14,  4],
       [10,  7],
       [ 6,  9]])

In [17]:
two_dim

array([[10, 18, 11, 17],
       [ 3, 13, 14,  4],
       [ 5, 13, 10,  7],
       [17,  3,  6,  9]])

In [20]:
np.hsplit(two_dim,[1])

[array([[10],
        [ 3],
        [ 5],
        [17]]),
 array([[18, 11, 17],
        [13, 14,  4],
        [13, 10,  7],
        [ 3,  6,  9]])]

In [21]:
two_dim

array([[10, 18, 11, 17],
       [ 3, 13, 14,  4],
       [ 5, 13, 10,  7],
       [17,  3,  6,  9]])

In [22]:
np.vsplit(two_dim,2)

[array([[10, 18, 11, 17],
        [ 3, 13, 14,  4]]),
 array([[ 5, 13, 10,  7],
        [17,  3,  6,  9]])]

In [23]:
np.vsplit(two_dim,[2,3])

[array([[10, 18, 11, 17],
        [ 3, 13, 14,  4]]),
 array([[ 5, 13, 10,  7]]),
 array([[17,  3,  6,  9]])]

In [24]:
## converting 2D to 1D array

In [25]:
one_dim= np.arange(0,12)

In [27]:
two_dim=one_dim.reshape(3,4)

In [28]:
two_dim

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
one_dim= np.ravel(two_dim,order='f')

In [36]:
one_dim

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [40]:
one_dim=two_dim.reshape(-1,order='c')

In [41]:
one_dim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Three Dimensional Array

In [44]:
three_dim=np.array([[[1,2,3],[3,4,5]],[[6,7,8],[9,10,11]]])

In [45]:
three_dim

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [46]:
three_dim.ndim

3

In [47]:
three_dim.shape

(2, 2, 3)

In [48]:
three_dim.size

12

In [49]:
three_dim[0,0,2]

3

In [53]:
three_dim

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [57]:
three_dim[:,0]

array([[1, 2, 3],
       [6, 7, 8]])

In [58]:
## deletion

In [59]:
three_dim

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [65]:
np.delete(three_dim,0,axis=1)

array([[[ 3,  4,  5]],

       [[ 9, 10, 11]]])

In [66]:
np.delete(three_dim,1,axis=2)

array([[[ 1,  3],
        [ 3,  5]],

       [[ 6,  8],
        [ 9, 11]]])

In [61]:
np.delete(three_dim,1,axis=1)

array([[[1, 2, 3]],

       [[6, 7, 8]]])

In [63]:
three_dim

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [62]:
np.delete(three_dim,2,axis=2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 6,  7],
        [ 9, 10]]])

In [67]:
three_dim

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [68]:
np.delete(three_dim,0,axis=0)

array([[[ 6,  7,  8],
        [ 9, 10, 11]]])

In [69]:
three_dim[:,0,[0,2]]

array([[1, 3],
       [6, 8]])

In [70]:
three_dim

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [83]:
two_dim= three_dim.reshape(-1,12)

In [84]:
two_dim

array([[ 1,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [82]:
three_dim

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [97]:
one_dim=three_dim.reshape(-1)

In [98]:
one_dim

array([ 1,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [99]:
two_dim

array([[ 1,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [101]:
three_dim= np.random.randint(0,100,24).reshape(2,3,4)

In [102]:
three_dim

array([[[78, 18, 83, 41],
        [52, 40, 85,  1],
        [31, 11, 57, 40]],

       [[28, 66, 28, 52],
        [43, 40, 41, 75],
        [88, 53, 62, 78]]])

In [103]:
np.random.rand(2,3,3)

array([[[0.3867203 , 0.34820131, 0.54441505],
        [0.14294957, 0.36853649, 0.78274248],
        [0.73627183, 0.95962959, 0.08580586]],

       [[0.84177449, 0.15984699, 0.15054476],
        [0.38426033, 0.27878025, 0.30307232],
        [0.35533138, 0.81113549, 0.69178616]]])

In [104]:
two_dim= np.random.randint(0,100,12).reshape(3,4)

In [105]:
two_dim

array([[82, 76, 37, 71],
       [41, 38, 22, 18],
       [12,  4, 42, 12]])

In [107]:
np.sum(two_dim,axis=0)

array([135, 118, 101, 101])

In [108]:
np.sum(two_dim,axis=1)

array([266, 119,  70])

In [109]:
np.mean(two_dim,axis=0)

array([45.        , 39.33333333, 33.66666667, 33.66666667])

## Pandas

In [110]:
import pandas as pd

In [120]:
ser1= pd.Series(data=[90,100,80],index=['ajay','sanjay','ravi'])

In [121]:
ser1

ajay       90
sanjay    100
ravi       80
dtype: int64

In [123]:
ser1['ajay':'sanjay']

ajay       90
sanjay    100
dtype: int64

In [114]:
ser1['sanjay']=90

In [115]:
ser1

ajay      90
sanjay    90
ravi      86
dtype: int64

In [122]:
ser1[0]

90

In [124]:
ser1.index.name='name'

In [125]:
ser1

name
ajay       90
sanjay    100
ravi       80
dtype: int64

In [126]:
ser2= pd.Series(data=[50,50,50],index=['ajay','sanjay','ravi'])

In [129]:
ser1

name
ajay       90
sanjay    100
ravi       80
dtype: int64

In [133]:
ser1 + ser2

name
ajay      140
sanjay    150
ravi      130
dtype: int64

In [134]:
ser1

name
ajay       90
sanjay    100
ravi       80
dtype: int64

In [140]:
ser1[['ajay','ravi']]=[90,80]

In [141]:
ser1

name
ajay       90
sanjay    100
ravi       80
dtype: int64

In [158]:
dict1={'names':['sam','ravi','sanjay','ajay'],'age':[22,23,24,25],'location':['chennai','bengaluru','calcutta','mumbai']}

## DataFrame

In [157]:
df= pd.DataFrame(data={'names':['sam','ravi','sanjay','ajay'],'age':[22,23,24,25],'location':['chennai','bengaluru','calcutta','mumbai']},index=[1,2,3,4])

In [150]:
df

names  age   location
1     sam   22    chennai
2    ravi   23  bengaluru
3  sanjay   24   calcutta
4    ajay   25     mumbai

In [159]:
df1= pd.DataFrame(data=dict1)

In [160]:
df1

names  age   location
0     sam   22    chennai
1    ravi   23  bengaluru
2  sanjay   24   calcutta
3    ajay   25     mumbai

In [152]:
df.index.name='Ser_Num'

In [153]:
df

names  age   location
Ser_Num                        
1           sam   22    chennai
2          ravi   23  bengaluru
3        sanjay   24   calcutta
4          ajay   25     mumbai

In [161]:
df

names  age   location
1     sam   22    chennai
2    ravi   23  bengaluru
3  sanjay   24   calcutta
4    ajay   25     mumbai

In [163]:
df

names  age   location
1     sam   22    chennai
2    ravi   23  bengaluru
3  sanjay   24   calcutta
4    ajay   25     mumbai

In [164]:
df.iloc[0:2]

names  age   location
1   sam   22    chennai
2  ravi   23  bengaluru

In [166]:
df.iloc[0:3,0:2]

names  age
1     sam   22
2    ravi   23
3  sanjay   24

In [167]:
df.loc[1:3,'names':'age']

names  age
1     sam   22
2    ravi   23
3  sanjay   24

In [168]:
df

names  age   location
1     sam   22    chennai
2    ravi   23  bengaluru
3  sanjay   24   calcutta
4    ajay   25     mumbai

In [170]:
df.iloc[[0,2],[0,2]]

names  location
1     sam   chennai
3  sanjay  calcutta

In [171]:
df.loc[[1,3],['names','location']]

names  location
1     sam   chennai
3  sanjay  calcutta