In [2]:
square= lambda x: x**2

In [3]:
square(2)

4

In [4]:
def func(x):
    return x**2

In [5]:
list1=[1,2,3,4,5,6,7]

In [6]:
func= lambda x:['even' if x%2==0 else 'odd' for x in list1]

In [7]:
func(list1)

['odd', 'even', 'odd', 'even', 'odd', 'even', 'odd']

In [8]:
fact= lambda x: 1 if x==1 else fact(x-1)*x

In [12]:
fact(5)

120

In [13]:
## greatest of 2 numbers

In [14]:
fun= lambda x,y: x if x>y else y

In [15]:
fun(3,5)

5

## filter function

In [39]:
def fun(x):
    if x%2==1:
        return False
    elif x%2==0:
        return False
    else:
        return True

In [40]:
a=[1,2,3,4,5,6,7,8,10.5]

In [41]:
list(filter(fun,a))

[10.5]

## Map function


In [42]:
def func(x):
    return x**2

In [43]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 10.5]

In [44]:
list(map(func,a))

[1, 4, 9, 16, 25, 36, 49, 64, 110.25]

In [45]:
list(map(lambda x: x+2,a))

[3, 4, 5, 6, 7, 8, 9, 10, 12.5]

In [46]:
def func(x,y):
    return x*y

In [47]:
a=[1,2,3,4,5,6,7]
b=[4,5,6]

In [48]:
list(map(func,a,b))

[4, 10, 18]

## Exceptional Handling

In [57]:
num1= int(input('Enter the first number'))
num2= int(input('Enter the Second Number'))
try:
    div=num1/num2
    print('The Result is',div)
except ZeroDivisionError:
    print('The Number cannot be divided by zero')
    div=None
    print('The division is ',div)

Enter the first number2
Enter the Second Number0
The Number cannot be divided by zero
The division is  None


In [2]:
num1= input('Enter the first number')
num2= input('Enter the Second Number')
try:
    div=num1/num2
except TypeError:
    print('The String cannot be divided')
    div=None
    print('The division is ',div)

Enter the first number2
Enter the Second Number2
The String cannot be divided
The division is  None


## Numpy

In [3]:
import numpy as np

### one_dimensional_array

In [4]:
one_dim= np.array([1,2,3,4,5,6,7,8])

In [5]:
one_dim

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
type(one_dim)

numpy.ndarray

In [7]:
one_dim.ndim

1

In [8]:
one_dim.shape

(8,)

In [9]:
one_dim.size

8

In [10]:
one_dim

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
one_dim[7]

8

In [13]:
one_dim[4:8]

array([5, 6, 7, 8])

In [14]:
one_dim[5]=100

In [15]:
one_dim

array([  1,   2,   3,   4,   5, 100,   7,   8])

In [17]:
np.insert(one_dim,4,50)

array([  1,   2,   3,   4,  50,   5, 100,   7,   8])

In [18]:
np.delete(one_dim,4)

array([  1,   2,   3,   4, 100,   7,   8])

In [23]:
np.delete(one_dim,[3,5])

array([1, 2, 3, 5, 7, 8])

In [24]:
one_dim

array([  1,   2,   3,   4,   5, 100,   7,   8])

In [25]:
np.delete(one_dim,(4,5))

array([1, 2, 3, 4, 7, 8])

In [26]:
one_dim

array([  1,   2,   3,   4,   5, 100,   7,   8])

In [27]:
np.sum(one_dim)

130

In [28]:
np.mean(one_dim)

16.25

In [29]:
one_dim

array([  1,   2,   3,   4,   5, 100,   7,   8])

In [30]:
np.max(one_dim)

100

In [31]:
np.min(one_dim)

1

In [36]:
np.divide(one_dim,3)

array([ 0.33333333,  0.66666667,  1.        ,  1.33333333,  1.66666667,
       33.33333333,  2.33333333,  2.66666667])

In [37]:
np.add(one_dim,2)

array([  3,   4,   5,   6,   7, 102,   9,  10])

In [38]:
np.subtract(one_dim,2)

array([-1,  0,  1,  2,  3, 98,  5,  6])

### Two dimensional Array

In [39]:
two_dim= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [40]:
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
two_dim.ndim

2

In [42]:
two_dim.shape

(3, 3)

In [43]:
two_dim[1,1]

5

In [44]:
two_dim[2,2]

9

In [46]:
two_dim[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [48]:
two_dim[:,[0,2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [51]:
two_dim[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [52]:
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
two_dim[2,]=[10,20,30]

In [54]:
two_dim

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30]])

In [58]:
two_dim[:,2]=10

In [59]:
two_dim

array([[ 1,  2, 10],
       [ 4,  5, 10],
       [10, 20, 10]])

In [60]:
two_dim[1,1]=50

In [61]:
two_dim

array([[ 1,  2, 10],
       [ 4, 50, 10],
       [10, 20, 10]])

In [62]:
two_dim

array([[ 1,  2, 10],
       [ 4, 50, 10],
       [10, 20, 10]])

In [69]:
one_dim= np.arange(1,10,3)

In [70]:
one_dim

array([1, 4, 7])

In [77]:
two_dim= np.arange(0,12).reshape(4,3)

In [78]:
two_dim

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [87]:
np.random.randint(0,10,12).reshape(3,4)

array([[8, 3, 1, 8],
       [8, 8, 0, 5],
       [2, 9, 4, 0]])

In [97]:
np.random.random(9).reshape(3,3)

array([[0.660654  , 0.62954536, 0.59214074],
       [0.45544322, 0.84205647, 0.27168404],
       [0.05491982, 0.92059274, 0.789086  ]])

In [101]:
np.random.random_integers(0,5,10)

C:\Users\excel\AppData\Local\Temp\ipykernel_36204\3932849665.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 5 + 1) instead
  np.random.random_integers(0,5,10)


array([0, 1, 4, 1, 3, 2, 3, 2, 2, 2])

In [102]:
two_dim

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [104]:
two_dim.transpose()

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [107]:
two_dim=np.random.randint(0,4,4).reshape(2,2)

In [108]:
two_dim

array([[2, 3],
       [0, 3]])

In [110]:
## inverse of the matrix
np.linalg.inv(two_dim)

array([[ 0.5       , -0.5       ],
       [ 0.        ,  0.33333333]])

In [111]:
## delete an element from two_dim_ array

In [113]:
two_dim= np.random.randint(0,20,16).reshape(4,4)

In [114]:
two_dim

array([[19, 14, 10, 12],
       [15, 18,  1,  1],
       [13,  8, 12, 17],
       [ 5, 15,  3,  6]])

In [117]:
np.delete(two_dim,[1,2],axis=0)

array([[19, 14, 10, 12],
       [ 5, 15,  3,  6]])

In [119]:
np.delete(two_dim,[1,3],axis=1)

array([[19, 10],
       [15,  1],
       [13, 12],
       [ 5,  3]])

In [123]:
## identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [126]:
## one matrix
np.ones(shape=(3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [128]:
## zero matrix
np.zeros(shape=(3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [132]:
a= np.random.randint(0,10,4).reshape(2,2)
a

array([[8, 7],
       [5, 0]])

In [133]:
b= np.random.randint(0,20,4).reshape(2,2)
b

array([[11,  4],
       [ 9,  6]])

In [134]:
a+b

array([[19, 11],
       [14,  6]])

In [136]:
a

array([[8, 7],
       [5, 0]])

In [135]:
np.add(a,2)

array([[10,  9],
       [ 7,  2]])

In [137]:
a-b

array([[-3,  3],
       [-4, -6]])

In [138]:
a*b

array([[88, 28],
       [45,  0]])

In [139]:
a/b

array([[0.72727273, 1.75      ],
       [0.55555556, 0.        ]])

In [141]:
## matrix multiplication
a@b

array([[151,  74],
       [ 55,  20]])

## stacking of arrays

In [143]:
a

array([[8, 7],
       [5, 0]])

In [144]:
b

array([[11,  4],
       [ 9,  6]])

In [146]:
np.hstack([a,b])

array([[ 8,  7, 11,  4],
       [ 5,  0,  9,  6]])

In [147]:
np.vstack([a,b])

array([[ 8,  7],
       [ 5,  0],
       [11,  4],
       [ 9,  6]])

## splitting the arrays

In [148]:
two_dim

array([[19, 14, 10, 12],
       [15, 18,  1,  1],
       [13,  8, 12, 17],
       [ 5, 15,  3,  6]])

In [150]:
a,b=np.hsplit(two_dim,2)

In [151]:
a

array([[19, 14],
       [15, 18],
       [13,  8],
       [ 5, 15]])

In [152]:
b

array([[10, 12],
       [ 1,  1],
       [12, 17],
       [ 3,  6]])

In [153]:
two_dim

array([[19, 14, 10, 12],
       [15, 18,  1,  1],
       [13,  8, 12, 17],
       [ 5, 15,  3,  6]])

In [155]:
np.hsplit(two_dim,[1,2,3])

[array([[19],
        [15],
        [13],
        [ 5]]),
 array([[14],
        [18],
        [ 8],
        [15]]),
 array([[10],
        [ 1],
        [12],
        [ 3]]),
 array([[12],
        [ 1],
        [17],
        [ 6]])]

In [156]:
two_dim

array([[19, 14, 10, 12],
       [15, 18,  1,  1],
       [13,  8, 12, 17],
       [ 5, 15,  3,  6]])

In [158]:
np.vsplit(two_dim,[2,3])

[array([[19, 14, 10, 12],
        [15, 18,  1,  1]]),
 array([[13,  8, 12, 17]]),
 array([[ 5, 15,  3,  6]])]

In [159]:
two_dim

array([[19, 14, 10, 12],
       [15, 18,  1,  1],
       [13,  8, 12, 17],
       [ 5, 15,  3,  6]])

In [160]:
np.mean(two_dim)

10.5625

In [161]:
np.sum(two_dim)

169

In [162]:
np.max(two_dim)

19

In [163]:
np.min(two_dim)

1

In [165]:
two_dim

array([[19, 14, 10, 12],
       [15, 18,  1,  1],
       [13,  8, 12, 17],
       [ 5, 15,  3,  6]])

In [164]:
np.mean(two_dim,axis=0)

array([13.  , 13.75,  6.5 ,  9.  ])

In [166]:
np.mean(two_dim,axis=1)

array([13.75,  8.75, 12.5 ,  7.25])

In [167]:
## two dimensional to one_dim array

In [168]:
two_dim

array([[19, 14, 10, 12],
       [15, 18,  1,  1],
       [13,  8, 12, 17],
       [ 5, 15,  3,  6]])

In [173]:
## ORDER='C'--will take the row wise
## ORDER='F'--will take the column wise
one_dim= np.ravel(two_dim,order='C')

In [174]:
one_dim

array([19, 14, 10, 12, 15, 18,  1,  1, 13,  8, 12, 17,  5, 15,  3,  6])

In [175]:
two_dim

array([[19, 14, 10, 12],
       [15, 18,  1,  1],
       [13,  8, 12, 17],
       [ 5, 15,  3,  6]])

In [178]:
one_dim= two_dim.reshape(-1,order='C')

In [179]:
one_dim

array([19, 14, 10, 12, 15, 18,  1,  1, 13,  8, 12, 17,  5, 15,  3,  6])

In [180]:
## one_dimension to two_dim

In [181]:
one_dim= np.random.randint(0,20,12)

In [182]:
one_dim

array([ 3, 14,  5, 15, 19,  6, 12,  0, 18, 17,  8,  0])

In [185]:
two_dim= one_dim.reshape(3,4,order='C')

In [186]:
two_dim

array([[ 3, 14,  5, 15],
       [19,  6, 12,  0],
       [18, 17,  8,  0]])

In [187]:
two_dim

array([[ 3, 14,  5, 15],
       [19,  6, 12,  0],
       [18, 17,  8,  0]])

### three_dimensional_array

In [192]:
three_dim= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [193]:
three_dim

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [194]:
three_dim.ndim

3

In [195]:
three_dim.shape

(2, 2, 3)

In [197]:
three_dim.size

12

In [198]:
three_dim

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [199]:
three_dim[1,1,1]

11

In [200]:
three_dim[1,:,[1,2]]

array([[ 8, 11],
       [ 9, 12]])

In [206]:
three_dim[[0,1],0,1:3]

array([[2, 3],
       [8, 9]])

In [207]:
three_dim[[0,1],:,1:3]

array([[[ 2,  3],
        [ 5,  6]],

       [[ 8,  9],
        [11, 12]]])

In [208]:
three_dim

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [209]:
three_dim[0,1,1]=100

In [210]:
three_dim

array([[[  1,   2,   3],
        [  4, 100,   6]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])

In [211]:
three_dim[0,:,2]=[5,5]

In [215]:
three_dim

array([[[  1,   2,   5],
        [  4, 100,   5]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])

In [214]:
np.delete(three_dim,0,axis=0)

array([[[ 7,  8,  9],
        [10, 11, 12]]])

In [216]:
np.delete(three_dim,1,axis=1)

array([[[1, 2, 5]],

       [[7, 8, 9]]])