## NUMPY

In [1]:
import numpy as np

In [2]:
one_dim= np.array([1,2,3,4,5])

In [3]:
one_dim

array([1, 2, 3, 4, 5])

In [4]:
type(one_dim)

numpy.ndarray

In [5]:
one_dim.ndim

1

In [6]:
one_dim.shape

(5,)

In [7]:
one_dim.size

5

In [8]:
one_dim= np.array([2,4,6,8,10])
one_dim

array([ 2,  4,  6,  8, 10])

In [ ]:
one_dim

In [ ]:
one_dim

In [ ]:
one_dim/one_dim1

In [ ]:
one_dim1.max()

In [ ]:
one_dim1

In [ ]:
one_dim1.min()

In [ ]:
one_dim1.mean()

In [ ]:
np.max(one_dim)

In [ ]:
np.min(one_dim)

In [ ]:
np.mean(one_dim)

In [ ]:
np.median(one_dim)

In [ ]:
np.sum(one_dim)

In [10]:
one_dim

array([ 2,  4,  6,  8, 10])

In [11]:
np.insert(one_dim,2,100)

array([  2,   4, 100,   6,   8,  10])

In [12]:
one_dim

array([ 2,  4,  6,  8, 10])

In [13]:
one_dim[2:5]

array([ 6,  8, 10])

In [14]:
list=[1,2,3,4]

In [15]:
np.array(list)

array([1, 2, 3, 4])

In [16]:
one_dim=np.array([1,3,3,4,5,6,7,7,8])

In [17]:
np.unique(one_dim)

array([1, 3, 4, 5, 6, 7, 8])

In [30]:
one_dim

NameError: name 'one_dim' is not defined

In [29]:
del one_dim

In [31]:
list1=[]
n= int(input('Enter the count'))
for i in range(0,n):
    var= int(input('Enter the data'))
    list1.append(var)
    one_dim2=np.array(list1)
print(one_dim2)
    

Enter the count5
Enter the data1
Enter the data2
Enter the data3
Enter the data4
Enter the data5
[1 2 3 4 5]


In [32]:
one_dim2

array([1, 2, 3, 4, 5])

## Two_dimensional_array

In [89]:
two_dim= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [90]:
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
type(two_dim)

numpy.ndarray

In [92]:
two_dim.ndim

2

In [93]:
two_dim.shape

(3, 3)

In [94]:
two_dim.size

9

In [96]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [105]:
two_dim= np.arange(0,24,2).reshape(3,4)

In [178]:
two_dim

array([[1, 2],
       [3, 4]])

In [28]:
def fabin(x):
    if x<=1:
        return x
    else:
        return fabin(x-1)+fabin(x-2)
var= int(input('How many count'))
if var<=0:
    print('Enter Positive Number')
else:
    print('Fabinacco Pattern')
    for i in range(var):
        print(fabin(i))
    

How many count15
Fabinacco Pattern
0
1
1
2
3
5
8
13
21
34
55
89
144
233
377


In [25]:
for i in range(5):
    print(i)

0
1
2
3
4


In [33]:
two_dim

array([[ 1,  2],
       [32,  4]])

In [34]:
two_dim= np.arange(0,16).reshape(4,4)

In [35]:
two_dim

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
two_dim[2,2]

10

In [37]:
two_dim[3,1]

13

In [38]:
two_dim[0:3]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
two_dim[:,[1,3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

In [50]:
two_dim[[0,2],1:3]

array([[ 1,  2],
       [ 9, 10]])

In [41]:
two_dim

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
two_dim[[0,2],[[1],[3]]].transpose()

array([[ 1,  3],
       [ 9, 11]])

In [60]:
array.transpose()

array([[ 1,  3],
       [ 9, 11]])

In [62]:
two_dim[1:3,0:3]

array([[ 4,  5,  6],
       [ 8,  9, 10]])

In [64]:
two_dim

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [68]:
two_dim[1:4,[[1],[3]]]

array([[[ 5],
        [ 7]],

       [[ 9],
        [11]],

       [[13],
        [15]]])

In [66]:
two_dim

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [76]:
two_dim[:,1:]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [77]:
two_dim

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [82]:
np.delete(two_dim,[1,2],axis=0)

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [83]:
np.delete(two_dim,3,axis=1)

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [84]:
np.delete(two_dim,[1,3],axis=1)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

In [85]:
two_dim

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [86]:
two_dim.transpose()

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [87]:
np.transpose(two_dim)

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [88]:
np.max(two_dim)

15

In [91]:
np.argmax(two_dim,axis=1)

array([3, 3, 3, 3], dtype=int64)

In [106]:
two_dim=np.random.randint(0,10,12).reshape(3,4)

In [107]:
two_dim

array([[6, 7, 7, 5],
       [4, 5, 6, 9],
       [2, 0, 7, 3]])

In [108]:
np.argmax(two_dim,axis=0)

array([0, 0, 0, 1], dtype=int64)

In [109]:
np.argmax(two_dim,axis=1)

array([1, 3, 2], dtype=int64)

In [117]:
np.random.rand(3,4).round(2)

array([[0.76, 0.24, 0.46, 0.02],
       [0.77, 0.89, 0.21, 0.6 ],
       [0.92, 0.47, 0.2 , 0.4 ]])

In [119]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [120]:
np.zeros(shape=(3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [121]:
np.ones(shape=(3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [124]:
a= np.random.randint(2,10,4).reshape(2,2)

In [125]:
a

array([[2, 5],
       [3, 8]])

In [126]:
b= np.random.randint(2,20,4).reshape(2,2)

In [127]:
b

array([[15,  6],
       [ 5,  2]])

In [128]:
a+b

array([[17, 11],
       [ 8, 10]])

In [129]:
a-b

array([[-13,  -1],
       [ -2,   6]])

In [130]:
a*b

array([[30, 30],
       [15, 16]])

In [131]:
a/b

array([[0.13333333, 0.83333333],
       [0.6       , 4.        ]])

In [139]:
# matrix multiplication
a@b

array([[55, 22],
       [85, 34]])

In [133]:
# inverse of a matrix
np.linalg.inv(a)

array([[ 8., -5.],
       [-3.,  2.]])

In [134]:
a

array([[2, 5],
       [3, 8]])

In [135]:
b

array([[15,  6],
       [ 5,  2]])

In [137]:
np.hstack([a,b])

array([[ 2,  5, 15,  6],
       [ 3,  8,  5,  2]])

In [138]:
np.vstack([a,b])

array([[ 2,  5],
       [ 3,  8],
       [15,  6],
       [ 5,  2]])