In [50]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import pairwise_distances

In [5]:
df= pd.read_csv('Movie.csv')

In [6]:
df.head()

userId             movie  rating
0       3  Toy Story (1995)     4.0
1       6  Toy Story (1995)     5.0
2       8  Toy Story (1995)     4.0
3      10  Toy Story (1995)     4.0
4      11  Toy Story (1995)     4.5

In [9]:
df.shape

(8992, 3)

In [8]:
len(df.userId.unique())

4081

In [10]:
len(df.movie.unique())

10

In [11]:
len(df.rating.unique())

10

In [12]:
df.rating.value_counts()

rating
3.0    2736
4.0    2660
5.0    1394
3.5     679
2.0     542
4.5     374
2.5     277
1.0     212
1.5      61
0.5      57
Name: count, dtype: int64

In [17]:
df.groupby('movie')['rating'].count().sort_values(ascending=False).head()

movie
Toy Story (1995)    2569
GoldenEye (1995)    1548
Heat (1995)         1260
Jumanji (1995)      1155
Sabrina (1995)       700
Name: rating, dtype: int64

In [18]:
df.groupby('movie')['rating'].mean().sort_values(ascending=False).head()

movie
Toy Story (1995)       3.959323
Heat (1995)            3.836508
GoldenEye (1995)       3.427003
Sabrina (1995)         3.381429
Tom and Huck (1995)    3.352564
Name: rating, dtype: float64

In [21]:
df_1=df.pivot_table(index='userId',columns='movie',values='rating')
df_1

movie   Father of the Bride Part II (1995)  GoldenEye (1995)  \
userId                                                         
1                                      NaN               NaN   
2                                      NaN               NaN   
3                                      NaN               NaN   
4                                      NaN               4.0   
5                                      NaN               NaN   
...                                    ...               ...   
7115                                   4.0               NaN   
7116                                   3.5               NaN   
7117                                   NaN               3.0   
7119                                   NaN               NaN   
7120                                   NaN               NaN   

movie   Grumpier Old Men (1995)  Heat (1995)  Jumanji (1995)  Sabrina (1995)  \
userId                                                                         
1                           NaN          NaN             3.5             NaN   
2                           4.0          NaN             NaN             NaN   
3                           NaN          NaN             NaN             NaN   
4                           NaN          3.0             NaN             NaN   
5                           NaN          NaN             3.0             NaN   
...                         ...          ...             ...             ...   
7115                        NaN          NaN             NaN             NaN   
7116                        NaN          NaN             NaN             NaN   
7117                        4.0          5.0             NaN             3.0   
7119                        NaN          NaN             NaN             NaN   
7120                        NaN          NaN             4.0             4.0   

movie   Sudden Death (1995)  Tom and Huck (1995)  Toy Story (1995)  \
userId                                                               
1                       NaN                  NaN               NaN   
2                       NaN                  NaN               NaN   
3                       NaN                  NaN               4.0   
4                       NaN                  NaN               NaN   
5                       NaN                  NaN               NaN   
...                     ...                  ...               ...   
7115                    NaN                  NaN               NaN   
7116                    NaN                  NaN               4.0   
7117                    1.0                  NaN               4.0   
7119                    NaN                  NaN               5.0   
7120                    NaN                  NaN               4.5   

movie   Waiting to Exhale (1995)  
userId                            
1                            NaN  
2                            NaN  
3                            NaN  
4                            NaN  
5                            NaN  
...                          ...  
7115                         NaN  
7116                         NaN  
7117                         NaN  
7119                         NaN  
7120                         NaN  

[4081 rows x 10 columns]

In [24]:
df_2=df_1.fillna(0,axis=1)
df_2

movie   Father of the Bride Part II (1995)  GoldenEye (1995)  \
userId                                                         
1                                      0.0               0.0   
2                                      0.0               0.0   
3                                      0.0               0.0   
4                                      0.0               4.0   
5                                      0.0               0.0   
...                                    ...               ...   
7115                                   4.0               0.0   
7116                                   3.5               0.0   
7117                                   0.0               3.0   
7119                                   0.0               0.0   
7120                                   0.0               0.0   

movie   Grumpier Old Men (1995)  Heat (1995)  Jumanji (1995)  Sabrina (1995)  \
userId                                                                         
1                           0.0          0.0             3.5             0.0   
2                           4.0          0.0             0.0             0.0   
3                           0.0          0.0             0.0             0.0   
4                           0.0          3.0             0.0             0.0   
5                           0.0          0.0             3.0             0.0   
...                         ...          ...             ...             ...   
7115                        0.0          0.0             0.0             0.0   
7116                        0.0          0.0             0.0             0.0   
7117                        4.0          5.0             0.0             3.0   
7119                        0.0          0.0             0.0             0.0   
7120                        0.0          0.0             4.0             4.0   

movie   Sudden Death (1995)  Tom and Huck (1995)  Toy Story (1995)  \
userId                                                               
1                       0.0                  0.0               0.0   
2                       0.0                  0.0               0.0   
3                       0.0                  0.0               4.0   
4                       0.0                  0.0               0.0   
5                       0.0                  0.0               0.0   
...                     ...                  ...               ...   
7115                    0.0                  0.0               0.0   
7116                    0.0                  0.0               4.0   
7117                    1.0                  0.0               4.0   
7119                    0.0                  0.0               5.0   
7120                    0.0                  0.0               4.5   

movie   Waiting to Exhale (1995)  
userId                            
1                            0.0  
2                            0.0  
3                            0.0  
4                            0.0  
5                            0.0  
...                          ...  
7115                         0.0  
7116                         0.0  
7117                         0.0  
7119                         0.0  
7120                         0.0  

[4081 rows x 10 columns]

In [27]:
df_arr=cosine_similarity(df_2)

In [28]:
df_arr

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.55337157],
       [0.        , 1.        , 0.        , ..., 0.45883147, 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.45883147, 1.        ,
        0.62254302],
       ...,
       [0.        , 0.45883147, 0.45883147, ..., 1.        , 0.45883147,
        0.47607054],
       [0.        , 0.        , 1.        , ..., 0.45883147, 1.        ,
        0.62254302],
       [0.55337157, 0.        , 0.62254302, ..., 0.47607054, 0.62254302,
        1.        ]])

In [31]:
df_new=pd.DataFrame(df_arr)
df_new

0         1         2         3         4         5         6     \
0     1.000000  0.000000  0.000000  0.000000  1.000000  0.000000  0.000000   
1     0.000000  1.000000  0.000000  0.000000  0.000000  0.390567  0.707107   
2     0.000000  0.000000  1.000000  0.000000  0.000000  0.650945  0.000000   
3     0.000000  0.000000  0.000000  1.000000  0.000000  0.000000  0.000000   
4     1.000000  0.000000  0.000000  0.000000  1.000000  0.000000  0.000000   
...        ...       ...       ...       ...       ...       ...       ...   
4076  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4077  0.000000  0.000000  0.752577  0.000000  0.000000  0.489886  0.000000   
4078  0.000000  0.458831  0.458831  0.619422  0.000000  0.701884  0.567775   
4079  0.000000  0.000000  1.000000  0.000000  0.000000  0.650945  0.000000   
4080  0.553372  0.000000  0.622543  0.000000  0.553372  0.765455  0.391293   

          7         8         9     ...      4071      4072      4073  \
0     0.000000  0.000000  0.000000  ...  0.000000  0.000000  1.000000   
1     0.615457  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
2     0.492366  1.000000  0.874157  ...  0.000000  1.000000  0.000000   
3     0.615457  0.000000  0.388514  ...  0.800000  0.000000  0.000000   
4     0.000000  0.000000  0.000000  ...  0.000000  0.000000  1.000000   
...        ...       ...       ...  ...       ...       ...       ...   
4076  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
4077  0.370543  0.752577  0.657870  ...  0.000000  0.752577  0.000000   
4078  0.889532  0.458831  0.568212  ...  0.344124  0.458831  0.000000   
4079  0.492366  1.000000  0.874157  ...  0.000000  1.000000  0.000000   
4080  0.306519  0.622543  0.544201  ...  0.000000  0.622543  0.553372   

          4074      4075      4076      4077      4078      4079      4080  
0     0.707107  0.000000  0.000000  0.000000  0.000000  0.000000  0.553372  
1     0.000000  0.000000  0.000000  0.000000  0.458831  0.000000  0.000000  
2     0.707107  0.000000  0.000000  0.752577  0.458831  1.000000  0.622543  
3     0.000000  0.989949  0.000000  0.000000  0.619422  0.000000  0.000000  
4     0.707107  0.000000  0.000000  0.000000  0.000000  0.000000  0.553372  
...        ...       ...       ...       ...       ...       ...       ...  
4076  0.000000  0.000000  1.000000  0.658505  0.000000  0.000000  0.000000  
4077  0.532152  0.000000  0.658505  1.000000  0.345306  0.752577  0.468511  
4078  0.324443  0.648886  0.000000  0.345306  1.000000  0.458831  0.476071  
4079  0.707107  0.000000  0.000000  0.752577  0.458831  1.000000  0.622543  
4080  0.831497  0.000000  0.000000  0.468511  0.476071  0.622543  1.000000  

[4081 rows x 4081 columns]

In [32]:
df_new.index= df.userId.unique()
df_new.columns= df.userId.unique()

In [33]:
df_new

3         6         8         10        11        12        13    \
3     1.000000  0.000000  0.000000  0.000000  1.000000  0.000000  0.000000   
6     0.000000  1.000000  0.000000  0.000000  0.000000  0.390567  0.707107   
8     0.000000  0.000000  1.000000  0.000000  0.000000  0.650945  0.000000   
10    0.000000  0.000000  0.000000  1.000000  0.000000  0.000000  0.000000   
11    1.000000  0.000000  0.000000  0.000000  1.000000  0.000000  0.000000   
...        ...       ...       ...       ...       ...       ...       ...   
7044  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
7070  0.000000  0.000000  0.752577  0.000000  0.000000  0.489886  0.000000   
7080  0.000000  0.458831  0.458831  0.619422  0.000000  0.701884  0.567775   
7087  0.000000  0.000000  1.000000  0.000000  0.000000  0.650945  0.000000   
7105  0.553372  0.000000  0.622543  0.000000  0.553372  0.765455  0.391293   

          14        16        19    ...      6975      6979      6993  \
3     0.000000  0.000000  0.000000  ...  0.000000  0.000000  1.000000   
6     0.615457  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
8     0.492366  1.000000  0.874157  ...  0.000000  1.000000  0.000000   
10    0.615457  0.000000  0.388514  ...  0.800000  0.000000  0.000000   
11    0.000000  0.000000  0.000000  ...  0.000000  0.000000  1.000000   
...        ...       ...       ...  ...       ...       ...       ...   
7044  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
7070  0.370543  0.752577  0.657870  ...  0.000000  0.752577  0.000000   
7080  0.889532  0.458831  0.568212  ...  0.344124  0.458831  0.000000   
7087  0.492366  1.000000  0.874157  ...  0.000000  1.000000  0.000000   
7105  0.306519  0.622543  0.544201  ...  0.000000  0.622543  0.553372   

          7030      7031      7044      7070      7080      7087      7105  
3     0.707107  0.000000  0.000000  0.000000  0.000000  0.000000  0.553372  
6     0.000000  0.000000  0.000000  0.000000  0.458831  0.000000  0.000000  
8     0.707107  0.000000  0.000000  0.752577  0.458831  1.000000  0.622543  
10    0.000000  0.989949  0.000000  0.000000  0.619422  0.000000  0.000000  
11    0.707107  0.000000  0.000000  0.000000  0.000000  0.000000  0.553372  
...        ...       ...       ...       ...       ...       ...       ...  
7044  0.000000  0.000000  1.000000  0.658505  0.000000  0.000000  0.000000  
7070  0.532152  0.000000  0.658505  1.000000  0.345306  0.752577  0.468511  
7080  0.324443  0.648886  0.000000  0.345306  1.000000  0.458831  0.476071  
7087  0.707107  0.000000  0.000000  0.752577  0.458831  1.000000  0.622543  
7105  0.831497  0.000000  0.000000  0.468511  0.476071  0.622543  1.000000  

[4081 rows x 4081 columns]

In [34]:
np.fill_diagonal(df_arr,0)

In [35]:
df_arr

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.55337157],
       [0.        , 0.        , 0.        , ..., 0.45883147, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.45883147, 1.        ,
        0.62254302],
       ...,
       [0.        , 0.45883147, 0.45883147, ..., 0.        , 0.45883147,
        0.47607054],
       [0.        , 0.        , 1.        , ..., 0.45883147, 0.        ,
        0.62254302],
       [0.55337157, 0.        , 0.62254302, ..., 0.47607054, 0.62254302,
        0.        ]])

In [36]:
df_new

3         6         8         10        11        12        13    \
3     0.000000  0.000000  0.000000  0.000000  1.000000  0.000000  0.000000   
6     0.000000  0.000000  0.000000  0.000000  0.000000  0.390567  0.707107   
8     0.000000  0.000000  0.000000  0.000000  0.000000  0.650945  0.000000   
10    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
11    1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
...        ...       ...       ...       ...       ...       ...       ...   
7044  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
7070  0.000000  0.000000  0.752577  0.000000  0.000000  0.489886  0.000000   
7080  0.000000  0.458831  0.458831  0.619422  0.000000  0.701884  0.567775   
7087  0.000000  0.000000  1.000000  0.000000  0.000000  0.650945  0.000000   
7105  0.553372  0.000000  0.622543  0.000000  0.553372  0.765455  0.391293   

          14        16        19    ...      6975      6979      6993  \
3     0.000000  0.000000  0.000000  ...  0.000000  0.000000  1.000000   
6     0.615457  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
8     0.492366  1.000000  0.874157  ...  0.000000  1.000000  0.000000   
10    0.615457  0.000000  0.388514  ...  0.800000  0.000000  0.000000   
11    0.000000  0.000000  0.000000  ...  0.000000  0.000000  1.000000   
...        ...       ...       ...  ...       ...       ...       ...   
7044  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
7070  0.370543  0.752577  0.657870  ...  0.000000  0.752577  0.000000   
7080  0.889532  0.458831  0.568212  ...  0.344124  0.458831  0.000000   
7087  0.492366  1.000000  0.874157  ...  0.000000  1.000000  0.000000   
7105  0.306519  0.622543  0.544201  ...  0.000000  0.622543  0.553372   

          7030      7031      7044      7070      7080      7087      7105  
3     0.707107  0.000000  0.000000  0.000000  0.000000  0.000000  0.553372  
6     0.000000  0.000000  0.000000  0.000000  0.458831  0.000000  0.000000  
8     0.707107  0.000000  0.000000  0.752577  0.458831  1.000000  0.622543  
10    0.000000  0.989949  0.000000  0.000000  0.619422  0.000000  0.000000  
11    0.707107  0.000000  0.000000  0.000000  0.000000  0.000000  0.553372  
...        ...       ...       ...       ...       ...       ...       ...  
7044  0.000000  0.000000  0.000000  0.658505  0.000000  0.000000  0.000000  
7070  0.532152  0.000000  0.658505  0.000000  0.345306  0.752577  0.468511  
7080  0.324443  0.648886  0.000000  0.345306  0.000000  0.458831  0.476071  
7087  0.707107  0.000000  0.000000  0.752577  0.458831  0.000000  0.622543  
7105  0.831497  0.000000  0.000000  0.468511  0.476071  0.622543  0.000000  

[4081 rows x 4081 columns]

In [42]:
d= pd.DataFrame({'marks':[10,20,30,40,50]},index=[1,2,3,4,5])

In [43]:
d

marks
1     10
2     20
3     30
4     40
5     50

In [44]:
d.idxmax()

marks    5
dtype: int64

In [46]:
df_new.idxmax()[0:10]

3       11
6      168
8       16
10    4047
11       3
12    6676
13    3559
14    4138
16       8
19    3603
dtype: int64

In [47]:
df[(df.userId==3) | (df.userId==11)]

userId             movie  rating
0          3  Toy Story (1995)     4.0
4         11  Toy Story (1995)     4.5
7446      11  GoldenEye (1995)     2.5

In [48]:
df[(df.userId==6) | (df.userId==168)]

userId                    movie  rating
1          6         Toy Story (1995)     5.0
60       168         Toy Story (1995)     4.5
3725       6  Grumpier Old Men (1995)     3.0
6464       6           Sabrina (1995)     5.0

In [52]:
pairwise_distances(df_2,metric='euclidean')

array([[0.        , 5.31507291, 5.31507291, ..., 9.39414711, 6.10327781,
        6.04152299],
       [5.31507291, 0.        , 5.65685425, ..., 7.74596669, 6.40312424,
        8.26135582],
       [5.31507291, 5.65685425, 0.        , ..., 7.74596669, 1.        ,
        5.67890835],
       ...,
       [9.39414711, 7.74596669, 7.74596669, ..., 0.        , 7.81024968,
        8.26135582],
       [6.10327781, 6.40312424, 1.        , ..., 7.81024968, 0.        ,
        5.67890835],
       [6.04152299, 8.26135582, 5.67890835, ..., 8.26135582, 5.67890835,
        0.        ]])

In [53]:
from sklearn.datasets import make_regression

In [56]:
x,y=make_regression()

In [58]:
y

array([ -17.24754914,  410.28806241, -229.45066537,   95.02648403,
        222.80284728,  137.97507108,  168.62071578,   65.71736926,
        123.40913271,   48.94591069,  -21.5803224 ,   26.67853989,
        -13.22773979,  -42.62059497, -135.18551193,   55.20036987,
       -129.09006858,   38.15498216,  123.69314456,  -11.41167327,
       -213.34610003,   30.79134786,  148.21070631,  112.21773668,
         32.82018793,  -39.77094169, -211.88436352,  233.43659554,
          2.14592214, -206.23011382,   49.95453062,  253.6337514 ,
        322.19870741, -176.49033559,   50.67523535,  -36.38338052,
        -10.69589046, -144.19695439,   35.62508582,  382.61838089,
         85.05824287,  -43.52498999,  -47.74306883,   -4.44218542,
       -125.37386374, -163.54827539,  136.98223799,   -7.49262581,
        260.56563153,    7.33041365, -235.46434456,  112.1742447 ,
        -60.73300517, -193.77605468,  135.49420337,  -87.052593  ,
          4.27098532,  -74.25334744,  -26.71897382,  -20.25520

In [61]:
## Pearson coefficient
from sklearn.feature_selection import r_regression

In [62]:
r_regression(x,y)

array([ 0.61030894, -0.06982727, -0.06349196, -0.11648609,  0.02009262,
        0.06083777,  0.098629  , -0.08153549,  0.19208215, -0.1802776 ,
        0.18020187, -0.01282942,  0.00660806, -0.08562507,  0.18917433,
        0.1521553 ,  0.02950051,  0.00917596,  0.00453128, -0.04799631,
       -0.03632773,  0.02196852, -0.17573335, -0.03304767,  0.10537787,
        0.0352584 , -0.14137602, -0.10591672,  0.01306024, -0.00145194,
        0.03269262, -0.11896567,  0.08271762,  0.02023223, -0.05911404,
       -0.07243162,  0.08320949,  0.00557339,  0.06369415,  0.13948079,
        0.00427543, -0.09862108,  0.00089097,  0.10521994, -0.07990034,
        0.16918286, -0.00942743,  0.08639196,  0.23664694,  0.5111598 ,
       -0.08334166,  0.17505838,  0.10202029,  0.23941057, -0.01612727,
       -0.02353006, -0.00929884, -0.09460125, -0.10776851, -0.13090156,
        0.00110747,  0.24783615, -0.00530729, -0.08749611,  0.00298691,
       -0.11340588, -0.12617541,  0.48587938, -0.15848904,  0.25