In [2]:
Exp=[1,2,3,4,5]
Salary=[1000,2400,3600,7800,10500]

In [3]:
import numpy as np

In [5]:
Exp_mean= np.mean(Exp)
Exp_mean

3.0

In [6]:
Exp_st_dev= np.std(Exp)
Exp_st_dev

1.4142135623730951

In [7]:
Exp_St_data= (Exp-Exp_mean)/Exp_st_dev

In [8]:
Exp_St_data

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [10]:
Salary_mean= np.mean(Salary)
Salary_mean

5060.0

In [11]:
Salary_std_dev= np.std(Salary)
Salary_std_dev

3543.783289085268

In [12]:
Salary_Std_Data= (Salary-Salary_mean)/Salary_std_dev
Salary_Std_Data

array([-1.14566825, -0.75061023, -0.41198908,  0.77318498,  1.53508258])

In [13]:
Exp_St_data

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [14]:
np.mean(Salary_Std_Data)

0.0

In [15]:
np.std(Salary_Std_Data)

1.0

In [16]:
np.mean(Exp_St_data)

0.0

In [17]:
np.std(Exp_St_data)

0.9999999999999999

In [18]:
Salary

[1000, 2400, 3600, 7800, 10500]

In [19]:
Salary_Std_Data

array([-1.14566825, -0.75061023, -0.41198908,  0.77318498,  1.53508258])